// Generated by build script, do not edit!
// This file is generated for the sole purpose of being included in Windows resource (.rc) files.
// DO NOT INCLUDE THIS FILE IN C++ CODE. Use #include "Runtime/Utilities/UnityConfiguration.h" instead.
#define UNITY_VERSION_BLD 15975364
#define UNITY_VERSION_UNDER_HASH "6000.4.7f1_f3c3c4248748"
#define UNITY_VERSION_PARENS_HASH "6000.4.7f1 (f3c3c4248748)"
#define UNITY_VERSION_WIN "6000.4.7.15975364"
